### PR TITLE
Teleport denied player to spawn

### PR DESCRIPTION
**Pull request by Yive**
Fixes a bug where players can't move and such without having an admin teleport them to spawn.

### CODE REVIEW

**Comment by MattBDev** [comment]
So this just stops players from glitching out when walking into a plot they are denied from?
Seems like a good fix if that's the case.

**Comment by Yive** [comment]
@MattBDev yeah since I guess some bug happens once they're denied and they use something like /tpa or /j to get back into the plot then they can't move or something similar (I haven't experienced it, only my players) If they tp out then they can't move either even on relogs, server needs to restart for it to be fixed.

**Comment by jomo** [comment]
Wouldn't it make more sense to teleport them (next) to the plot they're denied from?

**Comment by jomo** [comment]
Also, wouldn't this mean whenever you walk into a plot you're denied from, you get teleported to spawn?

**Comment by Yive** [comment]
@jomo that is true, sadly I don't know enough Java to code in such a thing. I'll do a small edit and just make it do the same as the other denied events below the modified one.

**Comment by MattBDev** [comment]
@jomo I am actually working on teleporting them to outside the plot they are denied from.

**Comment by jomo** [comment]
@MattBDev didn't @Yive already fix this in [Small edit](Yive/PlotMe/commit/ae793e1389a119c67e30d630612b10f0878290a1)?

**Comment by ZachBora** [comment]
I've had the code teleport to the plot home before and it isn't very fun. I know right now it glitches a little but /shrug, their problem for trying this much.

**Pull request closed without merging**
