### PR TITLE
Clear chest inventory before removing the plot

### PR DESCRIPTION
**Pull request by Runemoro**

### CODE REVIEW

**Comment by Runemoro** [comment]
Weird it added 2 commits

**Comment by Runemoro** [comment]
Sorry. I clicked Close & Comment button and can't reopen. I hate that button.

**Comment by ZachBora** [comment]
Oh sorry Runemoro I was already working on clearing chests and your code isn't wide enough, needs to work on any containers.

I've got the code down, working on some block that work differently like Jukebox.

The reason you have 2 commits is because you didn't get the last version before you submitted.

**Comment by Runemoro** [comment]
Ok, I'm going to work on something else then.

**Pull request closed without merging**
