### PR TITLE
Made PlotMe conform with WorldEdit's GPL

### PR DESCRIPTION
**Pull request by TomyLobo**
Hi, your "All rights reserved" license, as found [here](http://dev.bukkit.org/bukkit-plugins/plotme/), is not compatible with the license of one of your libraries (WorldEdit, GPL).
You must release your source (which you've done) and you must allow derivative works (which you've not done).

See also:
- [You have a GPL'ed program that I'd like to link with my code to build a proprietary program. Does the fact that I link with your program mean I have to GPL my program?](http://www.gnu.org/licenses/gpl-faq.html#LinkingWithGPL)
- [Does the GPL have different requirements for statically vs dynamically linked modules with a covered work?](http://www.gnu.org/licenses/gpl-faq.html#GPLStaticVsDynamic)

### CODE REVIEW

**Comment by TomyLobo** [comment]
PS: We're in the process of switching to LGPL, which would make your license ok.
Until we have contacted each and every contributor, however, you're not legally safe.

It's also a nice thing to share one's code for reuse by everyone else, so they can profit from it, just like profited from Bukkit and WorldEdit :)

**Comment by ZachBora** [comment]
Hi TomyLobo,

PlotMe is no longer being developed (It's now the PlotMe-Core and PlotMe-DefaultGenerator projects). I'll add this to the other project too.

**Comment by TomyLobo** [comment]
Cool, thanks :)

**Comment by TomyLobo** [comment]
I forgot to mention something the other day: GPL and the minecraft license are incompatible :/
You should either make a linking exception for Minecraft or switch to LGPL.

http://en.wikipedia.org/wiki/GPL_linking_exception

**Pull request merged**
