### PR TITLE
1.16!

### PR DESCRIPTION
**Pull request by heipiao233**
I lost some codes, and I used decompiler.

### CODE REVIEW

**Comment by ZachBora** [comment]
@heipiao233 wow this is a very old repo, there's a new version over in https://github.com/WorldCretornica which separates the WorldGen and the protection into PlotMe-Core and PlotMe-DefaultGenerator. They're also old, but contain some of the stuff you got in this PR.

Also don't know if you intended to push your changes to my own repo or yours.

**Comment by heipiao233** [comment]
> @heipiao233 wow this is a very old repo, there's a new version over in https://github.com/WorldCretornica which separates the WorldGen and the protection into PlotMe-Core and PlotMe-DefaultGenerator. They're also old, but contain some of the stuff you got in this PR.
> 
> Also don't know if you intended to push your changes to my own repo or yours.

The "newer" repo is archived, could I take over this project?

**Comment by ZachBora** [comment]
You can fork and let people know you're updating it. A project can become someone else's when it's the latest version. You don't need to take over the current branch to make it yours.

I've put these repos on github so people can see the code, fork if they want. If I give you the repo itself and something goes wrong my image could be tarnished. I prefer if you make your own fork and maintain that.

**Comment by heipiao233** [comment]
OK

发件人: ***@***.***>
发送时间: 2022年7月2日 3:23
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ZachBora/PlotMe] 1.16! (#53)


You can fork and let people know you're updating it. A project can become someone else's when it's the latest version. You don't need to take over the current branch to make it yours.

I've put these repos on github so people can see the code, fork if they want. If I give you the repo itself and something goes wrong my image could be tarnished. I prefer if you make your own fork and maintain that.

―

**Comment by heipiao233** [comment]
OK.

**Pull request closed without merging**
